version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: development
      POSTGRES_PASSWORD: password
volumes:
  pgdata: